/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as ShellDashboardRouteImport } from './routes/_shell.dashboard'
import { Route as ShellTransactionsRouteImport } from './routes/_shell.transactions'
import { Route as ShellExploitationsIndexRouteImport } from './routes/_shell.exploitations.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellDashboardRoute = ShellDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ShellRoute,
} as any)
const ShellTransactionsRoute = ShellTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => ShellRoute,
} as any)
const ShellExploitationsIndexRoute = ShellExploitationsIndexRouteImport.update({
  id: '/exploitations/',
  path: '/exploitations/',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connexion': typeof ConnexionRoute
  '/dashboard': typeof ShellDashboardRoute
  '/transactions': typeof ShellTransactionsRoute
  '/exploitations/': typeof ShellExploitationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connexion': typeof ConnexionRoute
  '/dashboard': typeof ShellDashboardRoute
  '/transactions': typeof ShellTransactionsRoute
  '/exploitations': typeof ShellExploitationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/connexion': typeof ConnexionRoute
  '/_shell/dashboard': typeof ShellDashboardRoute
  '/_shell/transactions': typeof ShellTransactionsRoute
  '/_shell/exploitations/': typeof ShellExploitationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/connexion' | '/dashboard' | '/transactions' | '/exploitations/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/connexion' | '/dashboard' | '/transactions' | '/exploitations'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/connexion'
    | '/_shell/dashboard'
    | '/_shell/transactions'
    | '/_shell/exploitations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
  ConnexionRoute: typeof ConnexionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/dashboard': {
      id: '/_shell/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ShellDashboardRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/transactions': {
      id: '/_shell/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof ShellTransactionsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/exploitations/': {
      id: '/_shell/exploitations/'
      path: '/exploitations'
      fullPath: '/exploitations/'
      preLoaderRoute: typeof ShellExploitationsIndexRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellDashboardRoute: typeof ShellDashboardRoute
  ShellTransactionsRoute: typeof ShellTransactionsRoute
  ShellExploitationsIndexRoute: typeof ShellExploitationsIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellDashboardRoute: ShellDashboardRoute,
  ShellTransactionsRoute: ShellTransactionsRoute,
  ShellExploitationsIndexRoute: ShellExploitationsIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
  ConnexionRoute: ConnexionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
